#' Validate state data consistency between two pipeline results
#'
#' Compares data for one state extracted from a regional pipeline result with
#' data generated by processing that state separately.
#'
#' @param regional_data Data frame containing multiple states.
#' @param state_data Data frame containing the separately processed state.
#' @param state Lowercase two-letter state code.
#' @param variables Character vector naming numeric variables to compare.
#' @param key_cols Character vector identifying observations uniquely.
#' @param state_col Character scalar naming the state column.
#' @param tolerance Maximum accepted scaled relative numeric difference. The
#'   scale is the greater of both absolute values and one.
#'
#' @return A named list containing `summary`, `variable_summary`,
#'   `key_mismatches`, and `value_mismatches`. Every tabular component is a
#'   tibble.
#'
#' @details
#' This function lives in `inst/validation/`, outside the package's `R/`
#' collection, and is therefore not part of the installed package's
#' namespace despite being documented with roxygen2 syntax. It depends only
#' on `dplyr`, `purrr`, `tibble`, and `checkmate` (no internal
#' extractmeteobr functions), so no changes were required to keep it aligned
#' with the current package API. Source it directly, or run
#' `devtools::load_all()` and call `source()` on this file, to make
#' `validate_regional_consistency()` available in the session.
validate_regional_consistency <- function(
    regional_data,
    state_data,
    state,
    variables = c("pr", "ETo"),
    key_cols = c("polygon_id", "date"),
    state_col = "state",
    tolerance = 1e-12
) {
  regional_data <- tibble::as_tibble(regional_data)
  state_data <- tibble::as_tibble(state_data)

  # `state` must already be a lowercase two-letter code, matching the
  # convention used by load_ibge_municipalities()/run_meteo_pipeline().
  checkmate::assert_string(state, pattern = "^[a-z]{2}$")
  checkmate::assert_character(variables, min.len = 1, unique = TRUE)
  checkmate::assert_character(key_cols, min.len = 1, unique = TRUE)
  checkmate::assert_string(state_col)
  checkmate::assert_number(tolerance, lower = 0, finite = TRUE)

  required_columns <- unique(c(key_cols, state_col, variables))
  checkmate::assert_names(
    names(regional_data),
    must.include = required_columns
  )
  checkmate::assert_names(
    names(state_data),
    must.include = required_columns
  )

  # Isolate the target state from the regional result (which mixes several
  # states) and sort both sources identically by `key_cols`, so that later
  # row-by-row comparisons are not affected by row order. `state_col` is
  # lowercased defensively, in case one of the two sources stores it with a
  # different case.
  regional_state <- regional_data |>
    dplyr::mutate(
      "{state_col}" := tolower(as.character(.data[[state_col]]))
    ) |>
    dplyr::filter(.data[[state_col]] == .env$state) |>
    dplyr::arrange(dplyr::across(dplyr::all_of(key_cols)))

  separate_state <- state_data |>
    dplyr::mutate(
      "{state_col}" := tolower(as.character(.data[[state_col]]))
    ) |>
    dplyr::filter(.data[[state_col]] == .env$state) |>
    dplyr::arrange(dplyr::across(dplyr::all_of(key_cols)))

  checkmate::assert_true(nrow(regional_state) > 0)
  checkmate::assert_true(nrow(separate_state) > 0)

  # `key_cols` (typically `polygon_id` and `date`) is expected to identify
  # exactly one row per source. A duplicate here would silently corrupt the
  # inner join used below to compare values, so it is counted explicitly
  # and later required to be zero for the validation to pass.
  regional_duplicate_count <- regional_state |>
    dplyr::count(dplyr::across(dplyr::all_of(key_cols))) |>
    dplyr::filter(n > 1L) |>
    nrow()
  state_duplicate_count <- separate_state |>
    dplyr::count(dplyr::across(dplyr::all_of(key_cols))) |>
    dplyr::filter(n > 1L) |>
    nrow()

  # Rows whose key exists in only one source indicate a coverage mismatch
  # (e.g. a missing municipality or a missing month in one of the pipeline
  # runs) rather than a numeric disagreement. These are reported separately
  # from `value_mismatches`, since an inner join below would silently drop
  # them without a value comparison ever being attempted.
  regional_only <- dplyr::anti_join(
    regional_state,
    separate_state,
    by = key_cols
  ) |>
    dplyr::select(dplyr::all_of(key_cols)) |>
    dplyr::mutate(source = "regional_only")
  state_only <- dplyr::anti_join(
    separate_state,
    regional_state,
    by = key_cols
  ) |>
    dplyr::select(dplyr::all_of(key_cols)) |>
    dplyr::mutate(source = "state_only")
  key_mismatches <- dplyr::bind_rows(regional_only, state_only) |>
    tibble::as_tibble()

  # Only keys present in both sources can be compared numerically; keys
  # already reported in `key_mismatches` are dropped here by the inner join.
  compared_data <- regional_state |>
    dplyr::select(dplyr::all_of(c(key_cols, variables))) |>
    dplyr::inner_join(
      separate_state |>
        dplyr::select(dplyr::all_of(c(key_cols, variables))),
      by = key_cols,
      suffix = c("_regional", "_state")
    )

  # For each meteorological variable, flag rows where the two pipeline runs
  # disagree either in missingness or in value.
  value_mismatches <- purrr::map_dfr(
    variables,
    function(variable) {
      regional_values <- compared_data[[paste0(variable, "_regional")]]
      state_values <- compared_data[[paste0(variable, "_state")]]
      absolute_difference <- abs(regional_values - state_values)
      # `comparison_scale` is the larger of the two magnitudes, floored at 1.
      # This keeps the relative difference well defined and interpretable
      # even when both values are close to zero, where a plain relative
      # difference (divided by one of the values) could blow up from
      # floating-point noise alone.
      comparison_scale <- pmax(
        abs(regional_values),
        abs(state_values),
        1,
        na.rm = TRUE
      )
      relative_difference <- absolute_difference / comparison_scale
      # NA in only one of the two sources is a disagreement in its own
      # right, even though no numeric difference can be computed for it.
      na_mismatch <- xor(is.na(regional_values), is.na(state_values))
      different <- na_mismatch |
        (!is.na(relative_difference) & relative_difference > tolerance)

      compared_data[different, key_cols, drop = FALSE] |>
        dplyr::mutate(
          variable = variable,
          regional_value = regional_values[different],
          state_value = state_values[different],
          absolute_difference = absolute_difference[different],
          relative_difference = relative_difference[different],
          na_mismatch = na_mismatch[different]
        )
    }
  ) |>
    tibble::as_tibble()

  # Recompute the same per-variable differences as above, but reduced to one
  # summary row per variable instead of one row per mismatch. This is kept
  # separate from `value_mismatches` because it also needs the differences
  # for rows that are *within* tolerance (to report `max_*_difference`),
  # which `value_mismatches` deliberately discards.
  variable_summary <- purrr::map_dfr(
    variables,
    function(variable) {
      regional_values <- compared_data[[paste0(variable, "_regional")]]
      state_values <- compared_data[[paste0(variable, "_state")]]
      absolute_difference <- abs(regional_values - state_values)
      comparison_scale <- pmax(
        abs(regional_values),
        abs(state_values),
        1,
        na.rm = TRUE
      )
      relative_difference <- absolute_difference / comparison_scale
      # Rows where either source is NA produce a non-finite difference
      # here; they are excluded from the magnitude summaries below because
      # they are already accounted for separately by `n_na_mismatches`.
      finite_differences <- absolute_difference[is.finite(absolute_difference)]
      finite_relative_differences <- relative_difference[
        is.finite(relative_difference)
      ]

      tibble::tibble(
        variable = variable,
        n_compared = length(regional_values),
        n_na_mismatches = sum(xor(is.na(regional_values), is.na(state_values))),
        max_absolute_difference = if (length(finite_differences) == 0L) {
          NA_real_
        } else {
          max(finite_differences)
        },
        max_relative_difference = if (
          length(finite_relative_differences) == 0L
        ) {
          NA_real_
        } else {
          max(finite_relative_differences)
        },
        # A variable only counts as consistent when every comparable value
        # is within tolerance AND no row has a one-sided NA. `is.na(...)`
        # here refers to `relative_difference` (NA when either input value
        # is NA), so it does not double-count with `is.finite()` above.
        values_equal = all(
          is.na(relative_difference) |
            relative_difference <= tolerance
        ) && !any(xor(is.na(regional_values), is.na(state_values)))
      )
    }
  )

  # The full validation passes only when the join keys were unique in both
  # sources (otherwise the value comparison itself would be unreliable),
  # every key was present in both sources, and every variable agreed within
  # tolerance.
  validation_passed <- regional_duplicate_count == 0L &&
    state_duplicate_count == 0L &&
    nrow(key_mismatches) == 0L &&
    all(variable_summary$values_equal)

  summary <- tibble::tibble(
    state = state,
    tolerance = tolerance,
    n_regional_rows = nrow(regional_state),
    n_state_rows = nrow(separate_state),
    n_regional_duplicate_keys = regional_duplicate_count,
    n_state_duplicate_keys = state_duplicate_count,
    n_key_mismatches = nrow(key_mismatches),
    n_value_mismatches = nrow(value_mismatches),
    validation_passed = validation_passed
  )

  # `summary` gives a single pass/fail verdict; `variable_summary` breaks it
  # down by variable; `key_mismatches` and `value_mismatches` provide the
  # row-level detail needed to investigate a failure.
  list(
    summary = summary,
    variable_summary = tibble::as_tibble(variable_summary),
    key_mismatches = key_mismatches,
    value_mismatches = value_mismatches
  )
}
